name: Generate and Deploy Docs

on:
  push:
    branches:
      - plugin-docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Doxygen
        run: doxygen Doxyfile
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./html
          config_file: Doxyfile
